Add DynamicBmp
embedded-graphics/embedded-graphics pull request #453
Opened 2020-10-27 19:44 UTC by rfuest

Hi! Thank you for helping out with Embedded Graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a simulator example(s) where applicable
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) and appropriate crate (`embedded-graphics`, `simulator`, `tinytga`, `tinybmp`) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

This PR adds `DynamicBmp` and reverts some previous changes by splitting `Bmp` into `Bmp` and `BmpRaw`. It also contains an extended parser for the BMP header which is required to distinguish between `Rgb555` and `Rgb565` images.

Because the code depends on #450 and is also missing some docs the PR is currently marked as a draft. I'll finish it after the other PR is merged.

2020-11-02 21:05 UTC, jamwaffles requested changes
I left some tiny nits so I can still feel relevant. Otherwise this looks good to go.

2020-11-02 21:05 UTC, jamwaffles commented on tinybmp/src/raw_bmp.rs
> +/// A BMP-format bitmap
```suggestion
/// A BMP-format bitmap.
```

2020-11-02 21:05 UTC, jamwaffles commented on tinybmp/src/raw_bmp.rs
> +    /// Image header
```suggestion
    /// Image header.
```

2020-11-02 21:05 UTC, jamwaffles commented on tinybmp/src/raw_bmp.rs
> +    /// Image data
```suggestion
    /// Image data.
```

2020-11-02 22:05 UTC, jamwaffles approved these changes
shipit

2020-11-03 16:35 UTC, merged

2020-11-03 16:35 UTC, rfuest commented
Thanks for the review!

2020-11-03 16:47 UTC, jamwaffles commented
Any time :)