Fix drawing of 90 degree args
embedded-graphics/embedded-graphics pull request #477
Opened 2020-11-14 20:56 UTC by rfuest

Thank you for helping out with embedded-graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

This PR makes drawing of 90° arcs consistent to drawing a quarter of a circle. Maybe this will help with #441. `Sector` will probably also need some tweaks, but that will be another PR.

2020-11-14 21:29 UTC, rfuest commented
I've converted this to a draft, because arcs with even diameters aren't handled correctly. There is a test for this case, but it makes the same wrong assumptions than the actual code.

2020-11-15 17:50 UTC, rfuest commented
It should now work as expected. The changes to the way the center point is calculated will also have some effect on `Sector` drawing, but I'll add additional tests for that in another dedicated PR.

2020-11-15 17:57 UTC, jamwaffles requested changes
I can't speak to the improvements on the algorithm, but the extra tests are a very welcome addition.

2020-11-15 17:57 UTC, jamwaffles commented on src/primitives/arc/linear_equation.rs
> +        //       a single quadrant. Is there a better solution to fix this?
```suggestion
        // FIXME: angle.tan() for 180.0 degrees isn't exactly 0 which causes problems when drawing
        //        a single quadrant. Is there a better solution to fix this?
```

A stupid nit, but makes for more accurate grepping

2020-11-15 18:11 UTC, jamwaffles approved these changes

2020-11-15 18:11 UTC, merged

2020-11-15 18:12 UTC, jamwaffles commented
Please let me know if you decide to pick up #405, otherwise I'll take another look at it.

2020-11-15 18:17 UTC, rfuest commented
> Please let me know if you decide to pick up #405, otherwise I'll take another look at it.

I haven't planed to, so give it a go if you like.