Fix link to migration guide from 0.6 to 0.7
embedded-graphics/embedded-graphics pull request #614
Opened 2021-07-11 21:37 UTC by sirhcel

Just fixes the link to the migration guide from 0.6 to 0.7 in `README.md`. Checked the link target in the preview of `README.md` manually.

2021-07-11 21:40 UTC, sirhcel commented
Reading through the checklist and deciding that they don't apply to this change, i forgot something: Saying a big thank you for providing and maintaining this crate! And especially providing a migration guide (which brought me here)! :)

2021-07-13 08:29 UTC, jamwaffles requested changes
Thanks for the fix! The readme is generated from `src/lib.rs`, so the [associated line 112 there](https://github.com/embedded-graphics/embedded-graphics/blob/master/src/lib.rs#L112) needs changing too. 

If you have `just` installed, running `just generate-readmes` will update everything, otherwise you can make the change manually in `src/lib.rs`.

2021-07-13 08:30 UTC, jamwaffles commented
>  a big thank you for providing and maintaining this crate! And especially providing a migration guide (which brought me here)! :)

Thank you from all of us :blush: I'm pretty proud of our docs, so it's great to hear they're useful!

2021-07-14 11:39 UTC, jamwaffles requested changes
Please add the same change to `src/lib.rs` or run `just generate-readmes` and commit both files - the build should pass then.

2021-07-14 11:46 UTC, sirhcel commented
Thank you for pointing me to `just`! I managed to re-generate the readmes but missed `git push --force` before re-requesting the review. I'm sorry for bothering you with this request!

Things should be good to go now.

2021-07-14 12:25 UTC, sirhcel commented
> Things should be good to go now.

Well ... apparently not. When running `just build-without-fmt-check` locally it fails at link checks:
```
[...]
cargo doc --workspace --features "nalgebra_support fixed" --no-deps
 Documenting embedded-graphics-core v0.3.2 ([...]/embedded-graphics/core)
 Documenting embedded-graphics v0.7.1 ([...]/embedded-graphics)
    Finished dev [unoptimized + debuginfo] target(s) in 2.84s
cargo deadlinks --dir target/doc/embedded_graphics
Found invalid urls in mono_font/struct.MonoFont.html:
        Fragment #tymethod.from_subset at mono_font/struct.MonoFont.html does not exist!
        Fragment #tymethod.vzip at mono_font/struct.MonoFont.html does not exist!
        Fragment #tymethod.is_in_subset at mono_font/struct.MonoFont.html does not exist!
        Fragment #tymethod.to_subset_unchecked at mono_font/struct.MonoFont.html does not exist!
[...]
error: Recipe `check-links` failed on line 77 with exit code 1
```
It does not look like there is a dead link/reference in the documentation because I can't find `from_subset` in the sources using `git grep` at all. This looks a bit mysterious to me at the moment.

2021-07-14 12:37 UTC, jamwaffles approved these changes
Thanks for the docs fix! 

> Well ... apparently not. When running just build-without-fmt-check locally it fails at link checks:

Don't worry about that - we've been seeing odd false positives like that for a while now so it's nothing to do with this PR :sweat_smile:

2021-07-14 12:37 UTC, merged