add rgb666 support
embedded-graphics/embedded-graphics pull request #621
Opened 2021-08-23 22:44 UTC by almindor

Thank you for helping out with embedded-graphics development! Please:

- [x] Check that you've added passing tests and documentation
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [x] Run `rustfmt` on the project
- [x] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

Adds `Rgb666` support.

2021-09-06 20:51 UTC, almindor commented
@jamwaffles ping? Also question, does it make any sense to create something like RawU18 for this?

2021-09-06 21:36 UTC, jamwaffles requested changes
Thanks for the nudge!

> does it make any sense to create something like RawU18 for this?

Yes, I think it does. The other colour types represent their exact storage so doing so with `Rgb666` keeps things consistent.

2021-09-06 21:36 UTC, jamwaffles commented on core/CHANGELOG.md
> +- Added `Rgb666` type support.
```suggestion
- [#621](https://github.com/embedded-graphics/embedded-graphics/pull/621) Added `Rgb666` color type support.
```

Please also add the same line to the top-level `CHANGELOG.md` too - these types are re-exported by e-g itself so it's good to let direct users know.

2021-09-06 21:37 UTC, jamwaffles commented
p.s. please rebase from master - the CI should start passing after #619 was merged.

2021-09-06 22:04 UTC, almindor commented
> p.s. please rebase from master - the CI should start passing after #619 was merged.

Seems there one more issue still in the CI for MSRV?

2021-09-06 22:14 UTC, almindor commented
I'm also unclear how to handle `ToBytes`for `RawU18` since padding is necessary for any kind of endianness swap logic to work.

Right now I do LE MCU to BE display this way:

```rust
        let mut iter = colors.into_iter().flat_map(|c| {
            let s = c.into_storage(); // bit-packed 18bits
                                      // we need to un-pack and pad with 2 bits each into 3 bytes of 6bit info
            let red = ((s & 0x3F) as u8) << 2;
            let green = (((s >> 6) & 0x3F) as u8) << 2;
            let blue = (((s >> 12) & 0x3F) as u8) << 2;
            [red, green, blue]
        });
```

2021-09-07 17:00 UTC, almindor commented
This should be good to go, the RawU18 representation is a bit funky tho when it comes to the endianness conversions, but then again it never really makes sense.

2021-09-08 21:18 UTC, bugadani commented
Could you please update the PR with a display that uses rgb666? Right now this looks like "yet another random color format". (I read your use case on matrix but IMO it would make sense to include it in the OP.)

2021-09-09 07:55 UTC, jamwaffles approved these changes
LGTM, thanks for your patience while I got round to this. I agree the `ToBytes` impl is a bit odd for 18 bit colours - it certainly makes more sense for multiples of 8 bits - but it might be useful for somebody, and it's consistent with the other RGB colours.

2021-09-09 07:56 UTC, jamwaffles commented
> Right now I do LE MCU to BE display this way:

Because `Rgb666` implements `RgbColor` you should be able to call `c.r()`, `c.g()` and `c.b()` to clean that code up a bit, FWIW.

2021-09-09 07:57 UTC, merged

2021-09-09 09:00 UTC, jamwaffles commented
This is released in e-g-core 0.3.3. e-g itself should pick the changes up with a `cargo update`.